pull_request_rules:
  - name: Merge PRs that are ready
    conditions:
      - status-success=Travis CI - Pull Request
      - status-success=typesafe-cla-validator
      - "#approved-reviews-by>=1"
      - "#review-requested=0"
      - "#changes-requested-reviews-by=0"
      - label!=status:block-merge
      - label=status:merge-when-green
    actions:
      merge:
        method: merge

  - name: Delete the PR branch and remove label after merge
    conditions:
      - merged
    actions:
      delete_head_branch: {}
      label:
        remove: [ "status:merge-when-green" ]

  - name: Labeling for Scala Steward PR's
    conditions:
      - author=scala-steward
    actions:
      label:
        add: [ "type:updates" ]

  - name: auto add wip
    conditions:
      # match a few flavours of wip
      - title~=^(\[wip\]( |:) |\[WIP\]( |:) |wip( |:) |WIP( |:)).*
    actions:
      label:
        add: ["status:block-merge"]
